"""Create users and cvs

Revision ID: fb021e71eb44
Revises:
Create Date: 2026-09-16 02:40:06.109686

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fb021e71eb44"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("google_id", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("google_id"),
    )
    op.create_table(
        "cvs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("file_type", sa.String(length=50), nullable=False),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("skills", sa.JSON(), nullable=False),
        sa.Column("job_titles", sa.JSON(), nullable=False),
        sa.Column("years_of_experience", sa.Integer(), nullable=True),
        sa.Column("education", sa.JSON(), nullable=False),
        sa.Column("languages", sa.JSON(), nullable=False),
        sa.Column("industries", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # op.drop_column('jobs', 'linkedin')
    # op.drop_column('jobs', 'point_of_contact')
    # op.drop_column('jobs', 'salary')
    # op.drop_column('jobs', 'email')
    # op.drop_column('jobs', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "jobs",
        sa.Column("phone", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    )
    op.add_column(
        "jobs",
        sa.Column("email", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    )
    op.add_column(
        "jobs",
        sa.Column("salary", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    )
    op.add_column(
        "jobs",
        sa.Column(
            "point_of_contact",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "jobs",
        sa.Column(
            "linkedin", sa.VARCHAR(length=500), autoincrement=False, nullable=True
        ),
    )
    op.drop_table("cvs")
    op.drop_table("users")
    # ### end Alembic commands ###
